Split up review/dcommit into separate commands.
This matches the airline style, and makes sense.

I was somewhat hestitent, because I liked the airline args objects
being separate from the command implementations, because then it
seemed more kosher to pass the args back into Git/RB methods
(e.g. to look at the groups/reviewers args).

Now we just pass the entire command itself, which seems a little
more tangled in theory, but probably not a big deal.

diff --git a/review-branch b/review-branch
--- a/review-branch
+++ b/review-branch
@@ -8,5 +8,8 @@ if [ -e ${SCRIPT_DIRECTORY}/${JAR} ]; then
   java -cp ${SCRIPT_DIRECTORY}/${JAR} $MAIN $*
 elif [ -e ${SCRIPT_DIRECTORY}/build/libs/${JAR} ]; then
   java -cp ${SCRIPT_DIRECTORY}/build/libs/${JAR} $MAIN $*
+else
+  echo "${JAR} not found in ${SCRIPT_DIRECTORY}"
+  exit 1
 fi
 
